-- =====================================================================
--  Securities Market Sentiment Analysis (SMSA) - Database schema
--  Engine : SQLite 3
-- =====================================================================
PRAGMA foreign_keys = ON;

-- ---------------------------------------------------------------------
-- 1. COMPANIES : master list of companies the texts talk about
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS companies (
    company_id    INTEGER PRIMARY KEY AUTOINCREMENT,
    company_name  TEXT    NOT NULL UNIQUE COLLATE NOCASE,
    created_at    TEXT    NOT NULL DEFAULT (datetime('now','localtime'))
);

-- ---------------------------------------------------------------------
-- 2. LLM_MODELS : every model / prompt combination used by the system
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS llm_models (
    model_id        INTEGER PRIMARY KEY AUTOINCREMENT,
    engine          TEXT    NOT NULL CHECK (engine IN ('groq','gemini','llm','finbert')),
    model_name      TEXT    NOT NULL,              -- e.g. openai/gpt-oss-120b, Qwen/Qwen2.5-1.5B-Instruct
    prompt_version  TEXT    NOT NULL DEFAULT 'n/a',-- e.g. fewshot-v2 (n/a for FinBERT)
    description     TEXT,
    created_at      TEXT    NOT NULL DEFAULT (datetime('now','localtime')),
    UNIQUE (engine, model_name, prompt_version)
);

-- ---------------------------------------------------------------------
-- 3. ANALYSIS_REQUESTS : each financial text submitted to the system
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS analysis_requests (
    request_id    INTEGER PRIMARY KEY AUTOINCREMENT,
    company_id    INTEGER REFERENCES companies(company_id) ON DELETE SET NULL,
    input_text    TEXT    NOT NULL,
    text_type     TEXT    NOT NULL DEFAULT 'other'
                  CHECK (text_type IN ('news','announcement','analyst','investor','social','other')),
    source        TEXT    NOT NULL DEFAULT 'web'
                  CHECK (source IN ('web','api','test')),
    client_ip     TEXT,
    submitted_at  TEXT    NOT NULL DEFAULT (datetime('now','localtime'))
);

-- ---------------------------------------------------------------------
-- 4. SENTIMENT_RESULTS : market-sentiment response returned by the LLM
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sentiment_results (
    result_id        INTEGER PRIMARY KEY AUTOINCREMENT,
    request_id       INTEGER NOT NULL UNIQUE
                     REFERENCES analysis_requests(request_id) ON DELETE CASCADE,
    model_id         INTEGER NOT NULL REFERENCES llm_models(model_id),
    sentiment        TEXT    NOT NULL CHECK (sentiment IN ('Positive','Negative','Neutral')),
    confidence       REAL    NOT NULL CHECK (confidence BETWEEN 0 AND 1),
    sentiment_score  REAL    NOT NULL CHECK (sentiment_score BETWEEN -1 AND 1), -- P(pos) - P(neg)
    prob_positive    REAL    NOT NULL,
    prob_negative    REAL    NOT NULL,
    prob_neutral     REAL    NOT NULL,
    detected_company TEXT,                -- company name identified by the LLM
    reasoning        TEXT,                -- short explanation produced by the LLM
    key_factors      TEXT,                -- JSON array of sentiment drivers
    raw_response     TEXT,                -- raw text generated by the model (audit trail)
    latency_ms       INTEGER,
    fallback_from    TEXT,                -- engines that failed before this one answered (NULL = none)
    created_at       TEXT    NOT NULL DEFAULT (datetime('now','localtime'))
);

-- ---------------------------------------------------------------------
-- 5. TEST_DATASET : labelled financial texts used to test the system
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS test_dataset (
    test_id             INTEGER PRIMARY KEY,
    text_type           TEXT NOT NULL
                        CHECK (text_type IN ('news','announcement','analyst','investor','social')),
    company_name        TEXT NOT NULL,
    input_text          TEXT NOT NULL,
    expected_sentiment  TEXT NOT NULL CHECK (expected_sentiment IN ('Positive','Negative','Neutral'))
);

-- ---------------------------------------------------------------------
-- 6. TEST_RUNS : one row per evaluation of the whole test data set
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS test_runs (
    run_id        INTEGER PRIMARY KEY AUTOINCREMENT,
    model_id      INTEGER NOT NULL REFERENCES llm_models(model_id),
    total_items   INTEGER NOT NULL DEFAULT 0,
    correct_items INTEGER NOT NULL DEFAULT 0,
    accuracy      REAL,
    macro_f1      REAL,
    avg_latency_ms REAL,
    started_at    TEXT NOT NULL DEFAULT (datetime('now','localtime')),
    finished_at   TEXT
);

-- ---------------------------------------------------------------------
-- 7. TEST_RUN_ITEMS : prediction for each test item inside a run
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS test_run_items (
    run_id     INTEGER NOT NULL REFERENCES test_runs(run_id) ON DELETE CASCADE,
    test_id    INTEGER NOT NULL REFERENCES test_dataset(test_id),
    result_id  INTEGER REFERENCES sentiment_results(result_id) ON DELETE SET NULL,
    predicted  TEXT    NOT NULL,
    expected   TEXT    NOT NULL,
    is_correct INTEGER NOT NULL CHECK (is_correct IN (0,1)),
    PRIMARY KEY (run_id, test_id)
);

-- ---------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_requests_company   ON analysis_requests(company_id);
CREATE INDEX IF NOT EXISTS idx_requests_submitted ON analysis_requests(submitted_at);
CREATE INDEX IF NOT EXISTS idx_results_sentiment  ON sentiment_results(sentiment);
CREATE INDEX IF NOT EXISTS idx_results_model      ON sentiment_results(model_id);

-- ---------------------------------------------------------------------
-- View : one flat row per analysed text (used by the History page / API)
-- ---------------------------------------------------------------------
DROP VIEW IF EXISTS v_sentiment_history;
CREATE VIEW v_sentiment_history AS
SELECT  r.result_id,
        q.request_id,
        q.submitted_at,
        q.source,
        q.text_type,
        c.company_name,
        r.detected_company,
        q.input_text,
        r.sentiment,
        r.confidence,
        r.sentiment_score,
        r.prob_positive,
        r.prob_negative,
        r.prob_neutral,
        r.reasoning,
        r.key_factors,
        r.latency_ms,
        r.fallback_from,
        m.engine,
        m.model_name,
        m.prompt_version
FROM        sentiment_results  r
JOIN        analysis_requests  q ON q.request_id = r.request_id
JOIN        llm_models         m ON m.model_id   = r.model_id
LEFT JOIN   companies          c ON c.company_id = q.company_id;
